swagger: "2.0"
info:
  title: "Swagger Demo"
  description: "Swagger Demo API"
  version: "1.0.0"
host: api-v2-int.chatso.io
basePath: /api/v2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: Health check
      responses:
        200:
          description: OK
