openapi: 3.0.0

info:
  title: Sample OpenAPI 3.0
  description: Demo description
  version: 0.0.1

servers:
  - url: http://api.example.com/v1
    description: Main (production) server
  - url: http://int-api.example.com/v1
    description: Staging server

paths:
  /users:
    get:
      description: Return a list of users.
      responses:
        200:
          description: A JSON array of users.
